# text_node_demo.py - Aligns OpenTUI packages/core/src/examples/text-node-demo.ts
# TextNode API: 4 examples (basic, nested, dynamic, document); keys 1-4, Space, R.

from __future__ import annotations

from typing import Any, List

from pytui.components.text_node import Span, bold, italic, underline

# StyledText = list of Span | str for Text content
StyledText = List[Span | str]

_parent_container: Any = None
_demo_text: Any = None
_instructions_text: Any = None
_status_text: Any = None
_renderer: Any = None
_current_example: int = 1
_dynamic_running: bool = False
_dynamic_counter: int = 0
_frame_callback_handle: Any = None
_MAX_COUNT = 20


def _example_1_spans() -> StyledText:
    """Example 1: Basic TextNode creation - individual spans with colors and styles."""
    return [
        Span(text="Basic TextNode Demo", fg="#58a6ff", bold=True),
        Span(text="\n\nCreating individual TextNodes with different styles:", fg="#8b949e"),
        Span(text="\n\nRed Text", fg="#ff7b72"),
        Span(text=" | Blue Text", fg="#79c0ff"),
        Span(text=" | Green Text", fg="#56d364"),
        Span(text=" | Yellow Background", fg="#000000", bg="#d29922"),
    ]


def _example_2_spans() -> StyledText:
    """Example 2: Nested composition - code block, comment, sentence with highlighting."""
    return [
        Span(text="Nested Composition Demo", fg="#58a6ff", bold=True),
        Span(text="\n\nBuilding complex text by nesting TextNodes:", fg="#8b949e"),
        Span(
            text="\n\nfunction calculateTotal(items) {\n  return items.reduce((sum, item) => {\n    return sum + item.price;\n  }, 0);\n}",
            fg="#f0f6fc",
            bg="#0d1117",
        ),
        Span(text="\n\n// This is a nested comment", fg="#8b949e"),
        bold(" with ", "#79c0ff"),
        Span(text="highlighting", fg="#ff7b72", underline=True),
        Span(text="\n\nThis demonstrates ", fg="#c9d1d9"),
        bold("and ", "#79c0ff"),
        Span(text="and ", fg="#c9d1d9"),
        Span(text="highlighting", fg="#ff7b72", underline=True),
        Span(text=" within the same text flow.", fg="#c9d1d9"),
    ]


def _example_3_spans(counter: int, status: str, progress_bar: str) -> StyledText:
    """Example 3: Dynamic updates - counter, status, progress bar."""
    return [
        Span(text="Dynamic Updates Demo", fg="#58a6ff", bold=True),
        Span(text="\n\nTextNodes can be updated dynamically:", fg="#8b949e"),
        bold(f"\n\nCounter: {counter}", "#56d364"),
        Span(f"\n\nStatus: {status}", fg="#79c0ff"),
        Span(f"\n\nProgress: [{progress_bar}]", fg="#d29922"),
    ]


def _example_4_spans() -> StyledText:
    """Example 4: Complex document structure with sections and emoji."""
    return [
        Span(text="Complex Document Demo", fg="#58a6ff", bold=True),
        Span(text="\n\nBuilding a complete document with TextNodes:", fg="#8b949e"),
        Span(text="\n\nProject Status Report", fg="#ffffff", bold=True),
        Span(text="\n\n  ", fg="#56d364"),
        Span(text="Progress", fg="#58a6ff", bold=True),
        Span(text=": 85% complete", fg="#c9d1d9"),
        Span(text="\n\n  ", fg="#d29922"),
        Span(text="Issues", fg="#ff7b72", bold=True),
        Span(text=": 2 minor issues found", fg="#c9d1d9"),
        Span(text="\n\n  ", fg="#56d364"),
        Span(text="Next Steps", fg="#58a6ff", bold=True),
        Span(text=": Code review and testing", fg="#c9d1d9"),
        Span(text="\n\n", fg="#30363d"),
        Span(text="Generated by PyTUI TextNode Demo", fg="#8b949e", italic=True),
    ]


def _update_dynamic() -> None:
    global _dynamic_counter, _demo_text
    if not _demo_text or _current_example != 3 or not _dynamic_running:
        return
    _dynamic_counter += 1
    if _dynamic_counter > _MAX_COUNT:
        _dynamic_counter = 0
    status = "Starting" if _dynamic_counter < 5 else ("Running" if _dynamic_counter < 15 else "Finishing")
    filled = min(10, int((_dynamic_counter / _MAX_COUNT) * 10))
    progress_bar = "\u2588" * filled + "\u2591" * (10 - filled)
    _demo_text.set_content(_example_3_spans(_dynamic_counter, status, progress_bar))


def _show_example_1() -> None:
    global _demo_text, _instructions_text, _current_example, _dynamic_running
    _current_example = 1
    _dynamic_running = False
    if _demo_text:
        _demo_text.clear()
        _demo_text.set_content(_example_1_spans())
    if _instructions_text:
        _instructions_text.set_content([
            bold("TextNode Demo", "#06b6d4"),
            Span(text="\n", fg="#c9d1d9"),
            Span(text=" Press ", fg="#c9d1d9"),
            Span(text="1-4", fg="#22c55e"),
            Span(text=" to see different examples  ", fg="#c9d1d9"),
            Span(text="SPACE", fg="#22c55e"),
            Span(text=" toggle dynamic  ", fg="#c9d1d9"),
            Span(text="R", fg="#22c55e"),
            Span(text=" reset  ", fg="#c9d1d9"),
            Span(text="ESC", fg="#22c55e"),
            Span(text=" exit\n", fg="#c9d1d9"),
            underline("Current:"),
            Span(text=" Example 1 - Basic TextNode Creation\nCreating individual TextNodes with different colors and styles.", fg="#c9d1d9"),
        ])


def _show_example_2() -> None:
    global _demo_text, _instructions_text, _current_example, _dynamic_running
    _current_example = 2
    _dynamic_running = False
    if _demo_text:
        _demo_text.clear()
        _demo_text.set_content(_example_2_spans())
    if _instructions_text:
        _instructions_text.set_content([
            bold("TextNode Demo", "#06b6d4"),
            Span(text="\n", fg="#c9d1d9"),
            Span(text=" Press ", fg="#c9d1d9"),
            Span(text="1-4", fg="#22c55e"),
            Span(text=" to see different examples  ", fg="#c9d1d9"),
            Span(text="SPACE", fg="#22c55e"),
            Span(text=" toggle dynamic  ", fg="#c9d1d9"),
            Span(text="R", fg="#22c55e"),
            Span(text=" reset\n", fg="#c9d1d9"),
            underline("Current:"),
            Span(text=" Example 2 - Nested Composition\nBuilding complex text structures by composing TextNodes.", fg="#c9d1d9"),
        ])


def _show_example_3() -> None:
    global _demo_text, _instructions_text, _current_example, _dynamic_counter, _dynamic_running
    _current_example = 3
    _dynamic_counter = 0
    _dynamic_running = True
    if _demo_text:
        _demo_text.clear()
        _demo_text.set_content(_example_3_spans(0, "Idle", "\u2591" * 10))
    if _instructions_text:
        _instructions_text.set_content([
            bold("TextNode Demo", "#06b6d4"),
            Span(text="\n", fg="#c9d1d9"),
            Span(text=" Press ", fg="#c9d1d9"),
            Span(text="1-4", fg="#22c55e"),
            Span(text=" to see different examples  ", fg="#c9d1d9"),
            Span(text="SPACE", fg="#22c55e"),
            Span(text=" toggle dynamic  ", fg="#c9d1d9"),
            Span(text="R", fg="#22c55e"),
            Span(text=" reset\n", fg="#c9d1d9"),
            underline("Current:"),
            Span(text=" Example 3 - Dynamic Updates\nTextNodes can be modified and changes reflected in real-time.", fg="#c9d1d9"),
        ])


def _show_example_4() -> None:
    global _demo_text, _instructions_text, _current_example, _dynamic_running
    _current_example = 4
    _dynamic_running = False
    if _demo_text:
        _demo_text.clear()
        _demo_text.set_content(_example_4_spans())
    if _instructions_text:
        _instructions_text.set_content([
            bold("TextNode Demo", "#06b6d4"),
            Span(text="\n", fg="#c9d1d9"),
            Span(text=" Press ", fg="#c9d1d9"),
            Span(text="1-4", fg="#22c55e"),
            Span(text=" to see different examples  ", fg="#c9d1d9"),
            Span(text="SPACE", fg="#22c55e"),
            Span(text=" toggle dynamic  ", fg="#c9d1d9"),
            Span(text="R", fg="#22c55e"),
            Span(text=" reset\n", fg="#c9d1d9"),
            underline("Current:"),
            Span(text=" Example 4 - Complex Document\nCreating complete documents with styled TextNode sections.", fg="#c9d1d9"),
        ])


def _toggle_dynamic() -> None:
    global _dynamic_running
    if _dynamic_running:
        _dynamic_running = False
        _update_status("Dynamic updates stopped")
    else:
        _show_example_3()
        _update_status("Dynamic updates started")


def _reset_demo() -> None:
    _show_example_1()
    _update_status("Demo reset")


def _update_status(message: str) -> None:
    global _status_text
    if _status_text:
        _status_text.set_content(message)


def _on_key(key_event: Any) -> None:
    name = getattr(key_event, "name", None) or (key_event.get("name") if isinstance(key_event, dict) else None)
    if not name:
        return
    name = str(name).lower()
    if name == "1":
        _show_example_1()
    elif name == "2":
        _show_example_2()
    elif name == "3":
        _show_example_3()
    elif name == "4":
        _show_example_4()
    elif name in (" ", "space"):
        _toggle_dynamic()
    elif name == "r":
        _reset_demo()
    elif name in ("escape", "esc"):
        if _renderer and hasattr(_renderer, "stop"):
            _renderer.stop()
        return
    _update_status(f"Last key: {name}")


def run(renderer: Any) -> None:
    global _parent_container, _demo_text, _instructions_text, _status_text, _frame_callback_handle, _renderer

    _renderer = renderer
    from pytui.components.box import Box
    from pytui.components.text import Text

    renderer.set_background_color("#0d1117")

    _parent_container = Box(
        renderer.context,
        {
            "id": "main_container",
            "width": 88,
            "height": 32,
            "flex_direction": "column",
            "backgroundColor": "#161b22",
            "z_index": 1,
        },
    )
    renderer.root.add(_parent_container)

    _demo_text = Text(
        renderer.context,
        {
            "id": "demoText",
            "content": [],
            "width": 84,
            "height": 20,
            "z_index": 2,
            "fg": "#f0f6fc",
        },
    )
    _parent_container.add(_demo_text)

    _instructions_text = Text(
        renderer.context,
        {
            "id": "instructions",
            "content": "",
            "width": 84,
            "height": 8,
            "fg": "#c9d1d9",
        },
    )
    _parent_container.add(_instructions_text)

    _status_text = Text(
        renderer.context,
        {
            "id": "status",
            "content": "Ready - Press 1-4 for examples",
            "width": 84,
            "height": 2,
            "fg": "#58a6ff",
        },
    )
    _parent_container.add(_status_text)

    _show_example_1()

    def _frame_cb(_delta_ms: float) -> None:
        _update_dynamic()

    _frame_callback_handle = _frame_cb
    renderer.set_frame_callback(_frame_cb)
    renderer.events.on("keypress", _on_key)


def destroy(renderer: Any) -> None:
    global _parent_container, _demo_text, _instructions_text, _status_text, _frame_callback_handle, _renderer

    try:
        renderer.events.remove_listener("keypress", _on_key)
    except Exception:
        pass
    if _frame_callback_handle is not None and hasattr(renderer, "remove_frame_callback"):
        try:
            renderer.remove_frame_callback(_frame_callback_handle)
        except Exception:
            pass
    if _parent_container and renderer.root:
        try:
            renderer.root.remove(_parent_container.id)
        except Exception:
            pass
    _parent_container = None
    _demo_text = None
    _instructions_text = None
    _status_text = None
    _renderer = None
    _frame_callback_handle = None
